version: '3'

services:
  mongo:
    image: mongo
    command: mongod --port ${MONGODB_PORT}
    restart: always
    network_mode: host
  server:
    depends_on:
      - mongo
    build:
      context: ./ChattR
      dockerfile: ./server/Dockerfile
    image: chattr-server
    restart: always
    network_mode: host
    environment:
      NODE_ENV: production
      PORT: ${SERVER_PORT}
      SESSION_SECRET: ${SESSION_SECRET}
      MONGODB_URL: mongodb://localhost:${MONGODB_PORT}/${MONGODB_COLLECTION_NAME}
      MONGODB_UPLOAD_BUCKET_NAME: ${MONGODB_UPLOAD_BUCKET_NAME}
      MONGODB_UPLOAD_MAX_FILE_SIZE: ${UPLOAD_MAX_FILE_SIZE}
      OPENVIDU_URL: http://localhost:5443
      OPENVIDU_SECRET: ${OPENVIDU_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
  client:
    depends_on:
      - server
    build:
      context: ./ChattR
      dockerfile: ./client/Dockerfile
    image: chattr-client
    restart: always
    network_mode: host
    environment:
      PORT: 5442
      SERVER_URL: http://localhost:${SERVER_PORT}
      MAX_BODY_SIZE: ${UPLOAD_MAX_FILE_SIZE}
